[[cli,Command line interface]]
== Command Line Interface

Even though SmuView has a graphical user interface, there is also a command line
interface that you can make use of. It is meant to provide functions for
convenience and debug purposes, not to replace the user interface itself.

Windows only shows output on the command line when the debug build is used.

Running
[listing, subs="normal"]
smuview -h

gives you a list of all available options.

Since SmuView can't automatically scan for devices connected to a COM port
(`ttySx` on Linux) or Ethernet, you can tell it to look for a specific device
using the `-d` or `--driver` parameter. Its usage is the same as for
`sigrok-cli`. All possible connection parameters are documented in the
https://sigrok.org/wiki/Connection_parameters[sigrok wiki]. For example:
[listing, subs="normal"]
smuview -d arachnid-labs-re-load-pro:conn=/dev/ttyUSB0

You also can start smuscripts from the command line with the `-s` or `--script`
parameter:
[listing, subs="normal"]
smuview -s /path/to/example_script.py

The remaining parameters are mostly for debug purposes:
[listing, subs="normal"]
-V / --version		Shows the release version
-l / --loglevel		Sets the libsigrok/libsigrokdecode log level (max is 5)
-D / --dont-scan	Do not auto-scan for devices and use -d spec only
-c / --clean		Do not restore previous settings on startup

Of these, `-D` / `--dont-scan` can be useful when SmuView gets stuck during
the startup device scan. No such scan will be performed then, allowing the
program to start up but you'll have to scan for your acquisition device(s)
manually before you can use them.

Another potentially useful option is `-c` / `--clean`, which can be used when
SmuView doesn’t start up and you don’t know what could cause this.

Thus, the combination of both parameters can be seen as some kind of "safe mode"
for SmuView:
[listing, subs="normal"]
smuview -c -D




