[[installation,Installation]]
== Installation

SmuView can be run on Linux, Windows and macOS. For Windows we provide
installers, for Linux we provide AppImage containers and for macOS DMGs. Both
the AppImage and the DMG can be run without the need to install anything.

You can choose between stable releases (by the time of writing, the last stable
version is 0.0.5) and continuous builds. We strongly recommend the use of the
continuous builds as they include bugfixes, new features and also an up-to-date
version of libsigrok with the latest available device drivers. Stable versions
are released infrequently in rather big intervals.

Check the https://github.com/knarfS/smuview/releases[SmuView download page] to
see which option is available for your platform.

=== Linux

You have two options to install SmuView, eiher you can use a pre-build AppImage
or you can build SmuView from source yourself.

[WARNING]
--
Whether you install SmuView using the AppImage or building from source, SmuView will
not be able to access USB and serial port devices unless it's run as `root`.
Since programs shouldn't be run as `root` unless absolutely necessary, we
provide udev configuration files that allows SmuView access to those devices
without being `root`.

Here's how you install them:
[listing, subs="normal"]
sudo bash
cd /etc/udev/rules.d/
wget -O 60-libsigrok.rules "'https://sigrok.org/gitweb/?p=libsigrok.git;a=blob_plain;f=contrib/60-libsigrok.rules'"
wget -O 61-libsigrok-plugdev.rules "'https://sigrok.org/gitweb/?p=libsigrok.git;a=blob_plain;f=contrib/61-libsigrok-plugdev.rules'"
wget -O 61-libsigrok-uaccess.rules "'https://sigrok.org/gitweb/?p=libsigrok.git;a=blob_plain;f=contrib/61-libsigrok-uaccess.rules'"
sudo udevadm control --reload-rules
--

==== AppImage

https://github.com/knarfS/smuview/releases[Download] and use the AppImage
which contains all required files and needs no installation:

[listing, subs="normal"]
chmod u+x SmuView-{sv_version}-x86_64.AppImage
./SmuView{sv_version}-x86_64.AppImage

Please be aware, however, that the AppImages are development releases at the
moment, so they always contain the latest development changes. While we do try
to keep the code base in a working state, it is sometimes unavoidable to
introduce bugs that show up in the AppImage builds. If you encounter something
that is odd to you, please download and install the latest release and check if
the issue still exists. If it does, feel free to
https://github.com/knarfS/smuview/issues[file a bug].

No system files are changed, so if you decide that you no longer want to use
SmuView, simply delete the AppImage. If you also want to remove the stored
settings, delete `~/.config/sigrok/SmuView.conf` as well.

==== Build from source

Uninstall any sigrok packages from your package manager and install all
necessary dependencies for
https://sigrok.org/wiki/Linux#Installing_the_requirements[libserialport],
https://sigrok.org/wiki/Linux#Installing_the_requirements_2[libsigrok] and
https://sigrok.org/wiki/Linux#Installing_the_requirements_6[SmuView].

[WARNING]
The linked build requirements are distro-specific and may or may not be out of
date, depending on which distro you use. Please check the official
https://sigrok.org/wiki/Building#Build_requirements[build requirements list] in
the sigrok wiki for the full list of requirements.

[WARNING]
--
Please make sure, that Python 3.x is your default Python interpreter. For Ubuntu
and Debian you can do so by installing the package `python-is-python3`:
[listing, subs="normal"]
sudo apt install python-is-python3
--

Now you can build SmuView from source with the help of a build script:

[listing, subs="normal"]
mkdir ~/sr
cd ~/sr
git clone --branch smuview --single-branch "'https://github.com/knarfS/sigrok-util.git'"
cd sigrok-util/cross-compile/linux
./sigrok-cross-linux-smuview
export LD_LIBRARY_PATH=~/sr/lib
~/sr/bin/smuview

No system files are changed, so if you decide that you no longer want to use
SmuView, simply delete the `~/sr` directory. If you also want to remove the
stored settings, delete `~/.config/sigrok/SmuView.conf` as well.

=== Windows

We offer installers for SmuView that contain everything you need to get started.
Simply download them from the
https://github.com/knarfS/smuview/releases[SmuView download page] and run them
as any other Windows installer.

Please be aware, however, that the Windows installers are development builds, so
they always contain the latest development changes. While we do try to keep the
code base in a working state, it is sometimes unavoidable to introduce bugs that
show up in the development builds. If you encounter something that is odd to
you, please download and install the latest release and check if the issue still
exists. If it does, feel free to
https://github.com/knarfS/smuview/issues/[file a bug].

After installation, you will find a program called Zadig in the start menu. By
default, certain devices recognized by Windows will have drivers installed for
them that SmuView cannot use. The purpose of Zadig is to let you change the
driver Windows uses for a particular device - for most devices you'll need to
choose WinUSB to use them with SmuView or the original proprietary Windows
driver to use it with whatever other software you access the device with. More
details are available https://sigrok.org/wiki/Windows[in the wiki].

In case your device doesn't show up in SmuView and you can't find it with a scan
either (see next chapter), check with Zadig whether the correct driver is
assigned for the device.

=== macOS

We offer a Apple Disk Image (DMG) for SmuvView that contains everything you need
to get started. Simply download them from the
https://github.com/knarfS/smuview/releases[SmuView download page] and run them.

Please be aware, however, that the DMG installers are development builds, so
they always contain the latest development changes. While we do try to keep the
code base in a working state, it is sometimes unavoidable to introduce bugs that
show up in the DMG builds. If you encounter something that is odd to you, please
download and install the latest release and check if the issue still exists. If
it does, feel free to https://github.com/knarfS/smuview/issues[file a bug].

No system files are changed, so if you decide that you no longer want to use
SmuView, simply delete the DMG file. If you also want the stored settings gone,
delete `~/Library/Preferences/SmuView.plist` as well.
