[[installation,Installation]]
== Installation

SmuView can be run on Linux and Windows. Mac OS X is not tested yet. For Windows
we provide installers and for Linux we provide AppImage containers that you can
run without the need to install anything. Check the
https://github.com/knarfS/smuview/releases[SmuView download page] to see which
option is available for your platform.

=== Linux

You have two options to install SmuView:

. https://github.com/knarfS/smuview/releases[Download] and use the AppImage
which contains all required files and needs no installation:
+
--
[listing, subs="normal"]
chmod u+x SmuView-{sv_version}-x86_64.AppImage
./SmuView{sv_version}-x86_64.AppImage

Please be aware, however, that the AppImages are development releases at the
moment, so they always contain the latest development changes. While we do try
to keep the code base in a working state, it is sometimes unavoidable to
introduce bugs that show up in the AppImage builds. If you encounter something
that is odd to you, please download and install the latest release and check if
the issue still exists. If it does, feel free to
https://github.com/knarfS/smuview/issues[file a bug].

No system files are changed, so if you decide that you no longer want to use
SmuView, simply delete the AppImage. If you also want to remove the stored
settings, delete `~/.config/sigrok/SmuView.conf` as well.
--

. Uninstall any sigrok packages from your package manager and build SmuView from
source:
+
--
[listing, subs="normal"]
_[install dependencies https://sigrok.org/wiki/Linux#Building[as listed on the wiki]]_
mkdir ~/sr
cd ~/sr
git clone --branch smuview --single-branch "'https://github.com/knarfS/sigrok-util.git'"
cd sigrok-util/cross-compile/linux
./sigrok-cross-linux-smuview
export LD_LIBRARY_PATH=~/sr/lib
~/sr/bin/smuview

No system files are changed, so if you decide that you no longer want to use
SmuView, simply delete the `~/sr` directory. If you also want to remove the
stored settings, delete `~/.config/sigrok/SmuView.conf` as well.
--

[WARNING]
--
If you install SmuView using the AppImage or building from source, SmuView will
not be able to access USB and serial port devices unless it's run as `root`.
Since programs shouldn't be run as `root` unless absolutely necessary, we
provide udev configuration files that allows SmuView access to those devices
without being `root`.

Here's how you install them:
[listing, subs="normal"]
sudo bash
cd /etc/udev/rules.d/
wget -O 60-libsigrok.rules "'https://sigrok.org/gitweb/?p=libsigrok.git;a=blob_plain;f=contrib/60-libsigrok.rules'"
wget -O 61-libsigrok-plugdev.rules "'https://sigrok.org/gitweb/?p=libsigrok.git;a=blob_plain;f=contrib/61-libsigrok-plugdev.rules'"
wget -O 61-libsigrok-uaccess.rules "'https://sigrok.org/gitweb/?p=libsigrok.git;a=blob_plain;f=contrib/61-libsigrok-uaccess.rules'"
sudo udevadm control --reload-rules
--

=== Windows

We offer installers for SmuView that contain everything you need to get started.
Simply download them from the
https://github.com/knarfS/smuview/releases[SmuView download page] and run them
as any other Windows installer.

Please be aware, however, that the Windows installers are development builds, so
they always contain the latest development changes. While we do try to keep the
code base in a working state, it is sometimes unavoidable to introduce bugs that
show up in the development builds. If you encounter something that is odd to
you, please download and install the latest release and check if the issue still
exists. If it does, feel free to
https://github.com/knarfS/smuview/issues/[file a bug].

After installation, you will find a program called Zadig in the start menu. By
default, certain devices recognized by Windows will have drivers installed for
them that SmuView cannot use. The purpose of Zadig is to let you change the
driver Windows uses for a particular device - for most devices you'll need to
choose WinUSB to use them with SmuView or the original proprietary Windows
driver to use it with whatever other software you access the device with. More
details are available https://sigrok.org/wiki/Windows[in the wiki].

In case your device doesn't show up in SmuView and you can't find it with a scan
either (see next chapter), check with Zadig whether the correct driver is
assigned for the device.

=== Mac OS X

We offer a Apple Disk Image (DMG) for SmuvView that contains everything you need
to get started. Simply download them from the
https://github.com/knarfS/smuview/releases[SmuView download page] and run them.

Please be aware, however, that the DMG installers are development builds, so
they always contain the latest development changes. While we do try to keep the
code base in a working state, it is sometimes unavoidable to introduce bugs that
show up in the DMG builds. If you encounter something that is odd to you, please
download and install the latest release and check if the issue still exists. If
it does, feel free to https://github.com/knarfS/smuview/issues[file a bug].

No system files are changed, so if you decide that you no longer want to use
SmuView, simply delete the DMG file. If you also want the stored settings gone,
delete `~/Library/Preferences/SmuView.plist` as well.
